#!/bin/bash

# Get the Python file name from the environment variable
pyfile=$PYFILE

# Check if the PYFILE environment variable is set
if [[ -z $pyfile ]]; then
    echo "PYFILE environment variable is not set."
    exit 1
fi

# Append the suffix '.pyc' to the Python file name
pycfile="${pyfile%.py}.pyc"

# Compile the Python script and generate the output file
python3 -m py_compile "$pyfile"

# Check if the compilation was successful
if [[ $? -eq 0 ]]; then
    # Move the compiled file to the correct name
    #mv "${pyfile}c" "$pycfile"
    echo "Compiling $pyfile ..."
else
    echo "Compilation failed."
    exit 1
fi
